#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
#@ load("@ytt:yaml", "yaml")
#@ load("inject_auth_proxy.lib.yml", "inject_secret")

apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.secret.name
  namespace: #@ data.values.secret.namespace
type: Opaque
data:
  #@ if data.values.authorization.enabled:
  config: #@ base64.encode(inject_secret(data.values.application, data.values.karaviAuthorizationProxy.defaultStartingPortRange, json.encode(yaml.decode(data.values.arrayconfig))))
  #@ else:
  config: #@ base64.encode(json.encode(yaml.decode(data.values.arrayconfig)))
  #@ end
