#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.secret.name
  namespace: #@ data.values.secret.namespace
type: Opaque
data:
  #@ if data.values.authorization.enabled:
  password: #@ base64.encode("-")
  username: #@ base64.encode("-")
  #@ else:
  password: #@ base64.encode(data.values.credentials.password)
  username: #@ base64.encode(data.values.credentials.username)
  #@ end
