#@data/values
---
application: powerstore
namespace: powerstore

#! CSI driver log level
#! Allowed values: "error", "warn"/"warning", "info", "debug", "error"
#! Default value: "debug"
logLevel: "debug"

#! CSI driver log format
#! Allowed values: "TEXT" or "JSON"
#! Default value: "JSON"
logFormat: "JSON"

#! imagePullPolicy: Policy to determine if the image should be pulled prior to starting the container.
#! Allowed values:
#!  Always: Always pull the image.
#!  IfNotPresent: Only pull the image if it does not already exist on the node.
#!  Never: Never pull the image.
#! Default value: None
imagePullPolicy: IfNotPresent

#! "defaultFsType" is used to set the default FS type which will be used
#! for mount volumes if FsType is not specified in the storage class
defaultFsType: ext4

#! "volumeNamePrefix" defines a string prepended to each volume created by the CSI driver.
volumeNamePrefix: csi

#! "nodeNamePrefix" defines a string prepended to each node registered by the CSI driver.
nodeNamePrefix: csi-node

#! "nodeIDPath" defines the path to file with node identifier (e.g. /etc/machine-id, /etc/hostname).
nodeIDPath: /etc/machine-id

#! "controller" allows to configure controller specific parameters
controller:
  #! "controller.nodeSelector" defines what nodes would be selected for pods of controller deployment
  #! Leave as blank to use all nodes
  nodeSelector:  

  #! "controller.tolerations" defines tolerations that would be applied to controller deployment
  #! Leave as blank to install controller on worker nodes
  tolerations:

  #! "controller.replicas" defines number of replicas of controller deployment
  replicas: 2

#! replication: allows to configure replication
replication:
  #! enabled: Enable/Disable replication feature
  #! Allowed values:
  #!   true: enable replication feature(install dell-csi-replicator sidecar)
  #!   false: disable replication feature(do not install dell-csi-replicator sidecar)
  #! Default value: true
  enabled: false

  #! image: Image to use for dell-csi-replicator. This shouldn't be changed
  #! Allowed values: string
  #! Default value: None
  image: dellemc/dell-csi-replicator:v1.0.0

  #! replicationContextPrefix: prefix to use for naming of resources created by replication feature
  #! Allowed values: string
  #! Default value: powerstore
  replicationContextPrefix: "powerstore"

  #! replicationPrefix: prefix to prepend to storage classes parameters
  #! Allowed values: string
  #! Default value: replication.storage.dell.com
  replicationPrefix: "replication.storage.dell.com"

#! "connection" allows to configure connection to storage array
connection:
  #! "connection.enableCHAP" allows to enable CHAP for iSCSI connections
  #! CHAP password will be autogenerated by driver
  enableCHAP: false

#! "nodeFCPortsFilterFile" is the name of the environment variable which store path to the file which
#! provide list of WWPN which should be used by the driver for FC connection on this node
#! example:
#! content of the file:
#!   21:00:00:29:ff:48:9f:6e,21:00:00:29:ff:48:9f:6e
#! If file not exist or empty or in invalid format, then the driver will use all available FC ports
nodeFCPortsFilterFile: /etc/fc-ports-filter

snapshot:
  enabled: false

#! allows to specify additional entries for hostAccess of NFS volumes. Both single IP address and subnet are valid entries.
#! valid entries: x.x.x.x/xx or x.x.x.x
externalAccess:

images:
  #! "images.driver" defines the container images used for the driver container.
  driver: dellemc/csi-powerstore:v2.0.0
